version: "3.9"
services:
  postgres:
    container_name: usermanagement-db
    image: postgres:latest
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: usermanagement
      POSTGRES_PASSWORD: usermanagement
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U usermanagement']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - usermanagement-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - usermanagement-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:

volumes:
  usermanagement-db:
  usermanagement-pgadmin: