version: "3.9"
services:
  usermanagement-db:
    container_name: usermanagement-db
    image: postgres:latest
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: usermanagement
      POSTGRES_PASSWORD: ${DB_PW_usermanagement}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U usermanagement'] # <<<---
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - usermanagement-db:/var/lib/postgresql/data
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - backend
    restart: unless-stopped
      
  usermanagement:
    image: usermanagement:latest
    depends_on:
      usermanagement-db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://usermanagement:5432/usermanagement?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: usermanagement
      SPRING_DATASOURCE_PASSWORD: ${DB_PW_usermanagement}
      KEYCLOAK_AUTH-SERVER-URL: https://${DOMAIN}/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  usermanagement-db:

 # Networks to be created to facilitate communication between containers
networks:
  backend:

