version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: ["start-dev"]
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin